#include"dathuc.cpp"
int main() {
    cout<<"=====CHUONG TRINH XU LY DA THUC====="<<endl<<endl;
    cout<<"So luong da thuc ban dau: "<<cDaThuc::GetDem()<<endl<<endl;
    cDaThuc dt1;
    cout<<"Da thuc 1 (mac dinh): "<<dt1;
    cDaThuc dt2(2);
    cout<<"Da thuc 2 (bac 2 voi he so mac dinh): "<<dt2;
    double hs[4]={1, 2, 3, 4}; 
    cDaThuc dt3(3, hs);
    cout<<"Da thuc 3 (tu mang he so): "<<dt3;
    cDaThuc dt4(dt3);
    cout<<"Da thuc 4 (copy tu da thuc 3): "<<dt4;
    cout<<"\nSo luong da thuc hien tai: "<<cDaThuc::GetDem()<<endl<<endl;
    cout<<"Nhap da thuc moi:"<<endl;
    cDaThuc dt5;
    cin>>dt5;
    cout<<"Da thuc vua nhap: "<<dt5;
    cout<<"Gan x bang: ";
    double x;
    cin>>x;
    cout<<"\nGia tri cua da thuc tai x = "<<x<<" la: ";
    cout<<dt5.TinhGiaTri(x)<<endl<<endl;
    cout<<"Thay doi bac cua da thuc 2 thanh 3"<<endl;
    dt2.SetN(3);
    cout<<"Da thuc 2 sau khi thay doi: "<<dt2;
    cout<<"Gan gia tri cua da thuc 3 cho da thuc 2"<<endl;
    dt2.SetHeSo(dt3);
    cout<<"Da thuc 2 sau khi gan: "<<dt2;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"\nPhep cong hai da thuc:"<<endl;
    cout<<"Nhap da thuc tiep theo: \n";
    cin>>dt3;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"Da thuc 5: " <<dt5;
    cDaThuc tong=dt3+dt5;
    cout<<"Tong hai da thuc: "<<tong;
    cout<<"\nPhep tru hai da thuc:"<<endl;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"Da thuc 5: "<<dt5;
    cDaThuc hieu=dt3-dt5;
    cout<<"Hieu hai da thuc: "<<hieu;
    cout<<"\nPhep nhan hai da thuc:"<<endl;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"Da thuc 5: "<<dt5;
    cDaThuc tich=dt3*dt5;
    cout<<"Tich hai da thuc: "<<tich;
    cout<<"\nPhep chia hai da thuc:"<<endl;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"Da thuc 5: "<<dt5;
    cDaThuc thuong=dt3/dt5;
    cout<<"Thuong hai da thuc: "<<thuong;
    cDaThuc du=dt3%dt5;
    cout<<"Du hai da thuc: "<<du;
    cout<<"\nDao ham va tich phan cua da thuc 5:"<<endl;
    cout<<"Da thuc 5: "<<dt5;
    cDaThuc daoHam=dt5.DaoHam();
    cout<<"Dao ham: "<<daoHam;
    cDaThuc tichPhan=dt5.TichPhan();
    cout<<"Tich phan (C=0): "<<tichPhan;
    cout<<"\nToi gian da thuc 3:"<<endl;
    cout<<"Truoc toi gian: "<<dt3;
    dt3.ToiGian();
    cout<<"Sau toi gian: "<<dt3;
    cout<<"\nSo sanh da thuc 3 va da thuc 5:"<<endl;
    cout<<"Da thuc 3: "<<dt3;
    cout<<"Da thuc 5: "<<dt5;
    cout<<"dt3 == dt5: "<<(dt3==dt5?"True":"False")<<endl;
    cout<<"dt3 > dt5: "<<(dt3>dt5?"True":"False")<<endl;
    cout<<"dt3 < dt5: "<<(dt3<dt5?"True":"False")<<endl;
    cout<<"\nSo luong da thuc hien tai: "<<cDaThuc::GetDem()<<endl;
    return 0;
}