#include"vector.cpp"
int main(){
    cout<<"\n===== CHUONG TRINH MINH HOA LOP CVECTOR =====\n";
    double arr1[]={1,2,3};
    double arr2[]={4,5,6};
    double arr3[]={0,0,0};
    CVector v1(3,arr1);
    CVector v2(3,arr2);
    CVector v3(3,arr3);
    CVector v4;
    cout<<"Vector v1: "<<v1<<endl;
    cout<<"Vector v2: "<<v2<<endl;
    cout<<"Vector v3: "<<v3<<endl;
    cout<<"Vector v4: "<<v4<<endl;
    cout<<"\n===== CAC PHEP TOAN CO BAN =====\n";
    cout<<"Nhap lan luot 2 vector"<<endl;
    cout<<"Nhap vector thu nhat: "<<endl; cin>>v1;
    cout<<"Nhap vector thu hai: "<<endl; cin>>v2;
    cout<<v1<<" + "<<v2<<" = "<<v1+v2<<endl;
    cout<<v1<<" - "<<v2<<" = "<<v1-v2<<endl;
    cout<<v1<<" * "<<v2<<" (tich vo huong) = "<<v1*v2<<endl;
    double x; cout<<"Nhap gia tri x: "; cin>>x;
    cout<<v1<<" * "<<x<<" = "<<v1*x<<endl;
    cout<<v2<<" / "<<x<<" = "<<v2/x<<endl;
    cout<<"\n===== CAC PHEP SO SANH =====\n";
    cout<<v1<<" == "<<v2<<": "<<(v1==v2?"true":"false")<<endl;
    cout<<v1<<" != "<<v2<<": "<<(v1!=v2?"true":"false")<<endl;
    cout<<v1<<" < "<<v2<<" (so sanh do dai): "<<(v1<v2?"true":"false")<<endl;
    cout<<"\n===== CAC PHUONG THUC KHAC =====\n";
    cout<<"Nhap vector thu 3: "<<endl; cin>>v3;
    cout<<v3<<" la vector 0: "<<(v3.IsZero()?"true":"false")<<endl;
    cout<<"Do dai "<<v1<<": "<<fixed<<setprecision(4)<<v1.DoDaiVecTor()<<endl;
    cout<<v1<<" chuan hoa: "<<v1.ChuanHoa()<<endl;
    cout<<"\n===== CAC PHEP TOAN NANG CAO ======\n";
    cout<<"Tich vo huong "<<v1<<" va "<<v2<<": "<<v1.TichVoHuong(v2)<<endl;
    cout<<"Tich co huong "<<v1<<" va "<<v2<<": "<<v1.TichCoHuong(v2)<<endl;
    double goc=v1.GocGiuaHaiVector(v2);
    cout<<"Goc giua "<<v1<<" va "<<v2<<": "<<fixed<<setprecision(4)<<goc<<" rad"<<endl;
    cout<<"                  "<<fixed<<setprecision(4)<<goc*180/pi<<" do"<<endl;
    cout<<"Chieu "<<v1<<" len "<<v2<<": "<<v1.PhepChieuVector(v2)<<endl;
    cout<<"\n===== VUONG GOC VA CUNG PHUONG =====\n";
    cout<<"v1:"<<v1<<endl;
    cout<<"v2:"<<v2<<endl;
    cout<<"v3:"<<v3<<endl;
    cout<<"v1 vuong goc v2:"<<(v1.KiemTraVuongGoc(v2)?"true":"false")<<endl;
    cout<<"v1 cung phuong v3:"<<(v1.KiemTraCungPhuong(v3)?"true":"false")<<endl;
    cout<<"\nSo luong doi tuong vector da tao:"<<CVector::GetDem()<<endl;
    return 0;
}